import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { BrowserRouter, Link, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, ArrowRight, Check, ChevronDown, Globe2, Headphones, Instagram, Mail, MapPin, Menu, MessageCircle, Plane, Search, ShieldCheck, Sparkles, Star, X, Clock3, Hotel, Users, Phone, CalendarDays, HeartHandshake, Navigation, CircleHelp } from 'lucide-react'
import './styles.css'

type Lang = 'ar' | 'fr'

const WHATSAPP = 'https://wa.me/213555000000'
const PHONE = '+213 555 00 00 00'
const EMAIL = 'contact@maarouftour.dz'

const images = {
  hero: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1800&q=85',
  dubai: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1000&q=85',
  istanbul: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1000&q=85',
  paris: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1000&q=85',
  umrah: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&w=1200&q=85',
  beach: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=85',
}

const offers = [
  { slug: 'istanbul', title: 'إسطنبول', fr: 'Istanbul', eyebrow: 'CITY ESCAPE', text: 'اكتشف مدينة تجمع بين التاريخ، البحر، التسوق والمذاق التركي.', duration: '7 أيام / 6 ليالٍ', image: images.istanbul, tag: 'وجهة مفضلة' },
  { slug: 'dubai', title: 'دبي', fr: 'Dubaï', eyebrow: 'PREMIUM CITY', text: 'تجربة حضرية بين الفخامة، المغامرة وأجمل الإطلالات.', duration: '6 أيام / 5 ليالٍ', image: images.dubai, tag: 'اختيار مميز' },
  { slug: 'paris', title: 'باريس', fr: 'Paris', eyebrow: 'EUROPE', text: 'أيام أنيقة في عاصمة الفن والموضة واللحظات التي لا تنسى.', duration: '5 أيام / 4 ليالٍ', image: images.paris, tag: 'موسمي' },
]

const destinations = [
  { slug: 'turkey', title: 'تركيا', fr: 'Turquie', count: 'استكشف إسطنبول، أنطاليا وكابادوكيا', image: images.istanbul },
  { slug: 'uae', title: 'الإمارات', fr: 'Émirats arabes unis', count: 'دبي وأبوظبي بتجربة مرنة', image: images.dubai },
  { slug: 'france', title: 'فرنسا', fr: 'France', count: 'باريس ومدن أوروبية ساحرة', image: images.paris },
  { slug: 'umrah', title: 'العمرة', fr: 'Omra', count: 'روحانية وتنظيم وراحة', image: images.umrah },
]

const services = [
  ['رحلات مخصصة', 'نصمم الرحلة حول وقتك، ميزانيتك وأسلوب سفرك.', Sparkles],
  ['حجز الفنادق', 'خيارات إقامة منتقاة مع مساعدة قبل وأثناء الرحلة.', Hotel],
  ['تذاكر الطيران', 'مقارنة مسارات مناسبة ومتابعة تفاصيل السفر.', Plane],
  ['برامج العمرة', 'تنظيم واضح وبرامج مريحة للعائلات والأفراد.', HeartHandshake],
]

const faqs = [
  ['هل يمكنني طلب رحلة مخصصة بالكامل؟', 'نعم. يمكنك إرسال الوجهة والتاريخ وعدد المسافرين وما تفضله، وسيتواصل معك الفريق لبناء المقترح المناسب.'],
  ['هل الأسعار المعروضة نهائية؟', 'الموقع يعرض نماذج وتجارب توضيحية فقط. السعر النهائي يتحدد حسب التوفر، التاريخ، الفندق والخدمات المطلوبة.'],
  ['هل يمكن التواصل عبر واتساب؟', 'نعم، واتساب هو أسرع قناة للاستفسار وطلب عرض مناسب.'],
  ['هل توفرون برامج عمرة؟', 'نعم، توجد صفحة مخصصة للعمرة لعرض البرنامج والخدمات والمعلومات الأساسية قبل التواصل.'],
]

function App() {
  const [lang, setLang] = useState<Lang>('ar')
  const [menu, setMenu] = useState(false)
  const location = useLocation()
  useEffect(() => {
    document.documentElement.lang = lang
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr'
    window.scrollTo({ top: 0, behavior: 'instant' as ScrollBehavior })
  }, [location.pathname, lang])

  return <>
    <Header lang={lang} setLang={setLang} menu={menu} setMenu={setMenu} />
    <main><Routes>
      <Route path="/" element={<Home lang={lang} />} />
      <Route path="/offres" element={<Offers lang={lang} />} />
      <Route path="/offres/:slug" element={<OfferDetail lang={lang} />} />
      <Route path="/destinations" element={<Destinations lang={lang} />} />
      <Route path="/destinations/:slug" element={<DestinationDetail lang={lang} />} />
      <Route path="/omra" element={<Umrah lang={lang} />} />
      <Route path="/services" element={<Services lang={lang} />} />
      <Route path="/a-propos" element={<About lang={lang} />} />
      <Route path="/faq" element={<FAQ lang={lang} />} />
      <Route path="/contact" element={<Contact lang={lang} />} />
      <Route path="*" element={<NotFound lang={lang} />} />
    </Routes></main>
    <Footer lang={lang} />
    <a className="wa-float" href={WHATSAPP} target="_blank" rel="noreferrer" aria-label="WhatsApp"><MessageCircle size={23}/><span>واتساب</span></a>
    <MobileNav lang={lang} />
  </>
}

function Header({ lang, setLang, menu, setMenu }: { lang: Lang; setLang: (l: Lang) => void; menu: boolean; setMenu: (v: boolean) => void }) {
  const links = lang === 'ar' ? [['الرئيسية','/'],['العروض','/offres'],['الوجهات','/destinations'],['العمرة','/omra'],['خدماتنا','/services'],['عن الشركة','/a-propos']] : [['Accueil','/'],['Offres','/offres'],['Destinations','/destinations'],['Omra','/omra'],['Services','/services'],['À propos','/a-propos']]
  return <header className="header"><div className="container nav">
    <Link to="/" className="brand" onClick={() => setMenu(false)}><span className="brand-mark"><Plane size={19}/></span><span><b>Maarouf</b><small>TOUR & TRAVEL</small></span></Link>
    <nav className={menu ? 'nav-links open' : 'nav-links'}>{links.map(([label, href]) => <Link key={href} to={href} onClick={() => setMenu(false)}>{label}</Link>)}<Link className="nav-cta" to="/contact" onClick={() => setMenu(false)}>{lang === 'ar' ? 'اطلب رحلتك' : 'Planifier mon voyage'} <ArrowLeft size={16}/></Link></nav>
    <div className="nav-actions"><button className="lang-btn" onClick={() => setLang(lang === 'ar' ? 'fr' : 'ar')}><Globe2 size={16}/>{lang === 'ar' ? 'FR' : 'AR'}</button><button className="menu-btn" onClick={() => setMenu(!menu)} aria-label="menu">{menu ? <X/> : <Menu/>}</button></div>
  </div></header>
}

function Home({ lang }: { lang: Lang }) {
  return <>
    <section className="hero"><img src={images.hero} alt="طائرة فوق السحاب"/><div className="hero-overlay"/><div className="route route-a"><span/><i/><b/></div><div className="container hero-content">
      <div className="eyebrow light"><span className="pulse"/> {lang === 'ar' ? 'سافر بثقة • عش التجربة' : 'VOYAGEZ AVEC CONFIANCE'}</div>
      <h1>{lang === 'ar' ? <>رحلتك القادمة<br/><em>تبدأ من هنا.</em></> : <>Votre prochaine<br/><em>aventure commence ici.</em></>}</h1>
      <p>{lang === 'ar' ? 'من أول فكرة إلى لحظة العودة، نهتم بالتفاصيل التي تجعل السفر أسهل وأجمل.' : 'De la première idée au retour, nous prenons soin de chaque détail.'}</p>
      <div className="hero-actions"><Link className="btn btn-primary" to="/contact">{lang === 'ar' ? 'خطط لرحلتي' : 'Planifier mon voyage'} <ArrowLeft size={18}/></Link><a className="btn btn-glass" href={WHATSAPP} target="_blank" rel="noreferrer"><MessageCircle size={18}/> WhatsApp</a></div>
      <div className="hero-trust"><span><ShieldCheck size={17}/> {lang === 'ar' ? 'مرافقة من البداية للنهاية' : 'Accompagnement complet'}</span><span><Headphones size={17}/> {lang === 'ar' ? 'دعم سريع' : 'Support réactif'}</span></div>
    </div><div className="scroll-cue"><span/> SCROLL TO EXPLORE</div></section>
    <QuickActions lang={lang}/><Planner lang={lang}/><OffersPreview lang={lang}/><UmrahStrip lang={lang}/><DestinationsPreview lang={lang}/><WhyUs lang={lang}/><FinalCTA lang={lang}/>
  </>
}

function QuickActions({ lang }: { lang: Lang }) { const items = [[Plane, lang==='ar'?'تذاكر الطيران':'Billets d’avion','أفضل مسار يناسبك'],[Hotel,lang==='ar'?'الفنادق':'Hôtels','إقامة مختارة بعناية'],[HeartHandshake,lang==='ar'?'العمرة':'Omra','برامج روحانية منظمة'],[Sparkles,lang==='ar'?'رحلة مخصصة':'Sur mesure','صمم تجربتك بنفسك']]; return <section className="quick"><div className="container quick-grid">{items.map(([Icon,title,sub],i)=><Link to={i===2?'/omra':'/contact'} className="quick-card" key={String(title)}><span className="iconbox"><Icon size={20}/></span><span><b>{title as string}</b><small>{sub as string}</small></span><ArrowLeft size={16}/></Link>)}</div></section> }

function Planner({ lang }: { lang: Lang }) { const [destination,setDestination]=useState(''); const [date,setDate]=useState(''); const [people,setPeople]=useState('2'); const [loading,setLoading]=useState(false); const navigate=useNavigate(); const submit=(e:FormEvent)=>{e.preventDefault();setLoading(true);setTimeout(()=>{setLoading(false);navigate('/contact',{state:{destination,date,people}})},450)}; return <section className="section planner"><div className="container"><div className="section-head center"><div className="eyebrow">SMART TRIP PLANNER</div><h2>{lang==='ar'?'قل لنا أين تريد أن تذهب.':'Tell us where you want to go.'}</h2><p>{lang==='ar'?'ثلاث معلومات فقط لنبدأ ببناء اقتراحك.':'Three details are enough to start.'}</p></div><form className="planner-box" onSubmit={submit}><label><span><Navigation size={16}/> {lang==='ar'?'الوجهة':'Destination'}</span><input required value={destination} onChange={e=>setDestination(e.target.value)} placeholder={lang==='ar'?'مثال: إسطنبول، دبي...':'e.g. Istanbul, Dubai...'}/></label><label><span><CalendarDays size={16}/> {lang==='ar'?'التاريخ التقريبي':'Travel date'}</span><input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label><span><Users size={16}/> {lang==='ar'?'المسافرون':'Travellers'}</span><select value={people} onChange={e=>setPeople(e.target.value)}><option>1</option><option>2</option><option>3</option><option>4</option><option>5+</option></select></label><button className="btn btn-dark" disabled={loading}>{loading?(lang==='ar'?'جارٍ التحضير...':'Preparing...'):(lang==='ar'?'ابدأ التخطيط':'Start planning')} <ArrowLeft size={18}/></button></form><div className="demo-note"><CircleHelp size={14}/> {lang==='ar'?'المعلومات والأسعار النهائية تتأكد بعد دراسة طلبك والتوفر.':'Final details and pricing are confirmed after checking your request and availability.'}</div></div></section> }

function OffersPreview({lang}:{lang:Lang}) { return <section className="section"><div className="container"><div className="section-head row"><div><div className="eyebrow">CURATED EXPERIENCES</div><h2>{lang==='ar'?'رحلات تستحق أن تُعاش.':'Trips worth remembering.'}</h2></div><Link className="text-link" to="/offres">{lang==='ar'?'كل العروض':'View all offers'} <ArrowLeft size={17}/></Link></div><div className="offer-grid">{offers.map(o=><Link className="offer-card" to={'/offres/'+o.slug} key={o.slug}><img src={o.image} alt={o.title}/><div className="offer-shade"/><span className="tag">{o.tag}</span><div className="offer-body"><small>{o.eyebrow}</small><h3>{lang==='ar'?o.title:o.fr}</h3><p>{o.text}</p><div><span><Clock3 size={14}/>{o.duration}</span><ArrowLeft size={19}/></div></div></Link>)}</div></div></section> }

function UmrahStrip({lang}:{lang:Lang}) { return <section className="umrah-strip"><img src={images.umrah} alt="العمرة"/><div className="strip-overlay"/><div className="container strip-content"><div><div className="eyebrow light">SPIRITUAL JOURNEY</div><h2>{lang==='ar'?'العمرة، براحة أكبر واهتمام بكل التفاصيل.':'Une Omra pensée pour votre sérénité.'}</h2><p>{lang==='ar'?'برنامج منظم، معلومات واضحة ومرافقة تساعدك على التركيز على رحلتك الروحانية.':'Un accompagnement clair pour vous concentrer sur l’essentiel.'}</p></div><Link className="btn btn-white" to="/omra">{lang==='ar'?'اكتشف برامج العمرة':'Découvrir l’Omra'} <ArrowLeft size={18}/></Link></div></section> }

function DestinationsPreview({lang}:{lang:Lang}) { return <section className="section soft"><div className="container"><div className="section-head center"><div className="eyebrow">DESTINATIONS</div><h2>{lang==='ar'?'العالم أقرب مما تتخيل.':'The world is closer than you think.'}</h2></div><div className="dest-grid">{destinations.map(d=><Link to={d.slug==='umrah'?'/omra':'/destinations/'+d.slug} className="dest-card" key={d.slug}><img src={d.image} alt={d.title}/><div><small>{d.count}</small><h3>{lang==='ar'?d.title:d.fr}</h3><span>{lang==='ar'?'استكشف':'Explore'} <ArrowLeft size={15}/></span></div></Link>)}</div></div></section> }

function WhyUs({lang}:{lang:Lang}) { const stats=[['01','فهم احتياجك'],['02','اقتراح واضح'],['03','تنسيق الحجز'],['04','متابعة الرحلة']]; return <section className="section why"><div className="container why-grid"><div><div className="eyebrow">THE MAAROUF WAY</div><h2>{lang==='ar'?'لسنا فقط نحجز لك.\nنحن نهتم بتجربتك.':'More than booking.\nWe care about your journey.'}</h2><p>{lang==='ar'?'نؤمن أن أفضل رحلة هي التي تشعر أنها صُممت لك. لذلك نبدأ بالاستماع، ثم نرتب التفاصيل بطريقة بسيطة وواضحة.':'The best trip should feel made for you. We listen first, then make the details simple and clear.'}</p><Link className="text-link" to="/a-propos">{lang==='ar'?'لماذا معروف تور؟':'Why Maarouf Tour?'} <ArrowLeft size={17}/></Link></div><div className="steps">{stats.map(([n,t])=><div className="step" key={n}><span>{n}</span><b>{lang==='ar'?t:['Understand you','Build your plan','Coordinate booking','Stay with you'][Number(n)-1]}</b><Check size={17}/></div>)}</div></div></section> }

function FinalCTA({lang}:{lang:Lang}) { return <section className="section"><div className="container final-cta"><div className="eyebrow">READY WHEN YOU ARE</div><h2>{lang==='ar'?'فكرة سفر واحدة قد تصبح أجمل ذكرى.':'One travel idea can become your best memory.'}</h2><p>{lang==='ar'?'أرسل لنا ما تفكر فيه، وسنبدأ من هناك.':'Tell us what you have in mind. We’ll take it from there.'}</p><div><Link className="btn btn-primary" to="/contact">{lang==='ar'?'ابدأ الآن':'Start now'} <ArrowLeft size={18}/></Link><a className="btn btn-outline" href={WHATSAPP} target="_blank" rel="noreferrer"><MessageCircle size={18}/> WhatsApp</a></div></div></section> }

function PageHero({kicker,title,text,image=images.hero}:{kicker:string;title:string;text:string;image?:string}) { return <section className="page-hero"><img src={image} alt=""/><div className="hero-overlay"/><div className="container page-hero-content"><div className="eyebrow light">{kicker}</div><h1>{title}</h1><p>{text}</p></div></section> }
function Offers({lang}:{lang:Lang}) { return <><PageHero kicker="CURATED OFFERS" title={lang==='ar'?'اختر التجربة، ونحن نهتم بالباقي.':'Choose the experience. We’ll handle the rest.'} text={lang==='ar'?'نماذج رحلات للإلهام، قابلة للتخصيص حسب طلبك.':'Inspiring trip concepts, tailored to your needs.'}/><section className="section"><div className="container"><div className="offer-grid large">{offers.map(o=><Link className="offer-card" to={'/offres/'+o.slug} key={o.slug}><img src={o.image} alt={o.title}/><div className="offer-shade"/><span className="tag">{o.tag}</span><div className="offer-body"><small>{o.eyebrow}</small><h3>{lang==='ar'?o.title:o.fr}</h3><p>{o.text}</p><div><span><Clock3 size={14}/>{o.duration}</span><ArrowLeft size={19}/></div></div></Link>)}</div><div className="demo-banner"><Sparkles size={18}/><span><b>{lang==='ar'?'بيانات تجريبية':'Demo content'}</b> — {lang==='ar'?'البرامج والأسعار النهائية يتم تأكيدها حسب التوفر والطلب.':'Programs and final prices are confirmed according to availability and your request.'}</span></div></div></section></> }
function OfferDetail({lang}:{lang:Lang}) { const {slug}=useParams(); const o=offers.find(x=>x.slug===slug)||offers[0]; return <><PageHero kicker={o.eyebrow} title={lang==='ar'?o.title:o.fr} text={o.text} image={o.image}/><section className="section"><div className="container detail-grid"><div><div className="eyebrow">TRIP CONCEPT</div><h2>{lang==='ar'?'تجربة مرنة، وليست قالبًا جاهزًا.':'A flexible experience, not a rigid package.'}</h2><p>{lang==='ar'?'هذا نموذج توضيحي لمساعدةك على تخيل الرحلة. بعد التواصل، نعدل المدة والإقامة والتنقل والأنشطة وفق احتياجاتك.':'This is a demo concept. After contacting us, we adapt duration, stay, transfers and activities to your needs.'}</p><div className="check-list"><span><Check/> {lang==='ar'?'تنسيق الرحلة حسب الطلب':'Tailored itinerary'}</span><span><Check/> {lang==='ar'?'خيارات إقامة متعددة':'Multiple stay options'}</span><span><Check/> {lang==='ar'?'دعم قبل وأثناء السفر':'Support before and during travel'}</span></div><Link className="btn btn-primary" to="/contact">{lang==='ar'?'اطلب عرضًا مخصصًا':'Request a tailored quote'} <ArrowLeft size={18}/></Link></div><div className="detail-card"><img src={o.image} alt={o.title}/><div><span><Clock3/> {o.duration}</span><span><Users/> {lang==='ar'?'حسب عدد المسافرين':'Based on travellers'}</span><span><ShieldCheck/> {lang==='ar'?'تفاصيل مؤكدة قبل الحجز':'Confirmed before booking'}</span></div></div></div></section></> }

function Destinations({lang}:{lang:Lang}) { return <><PageHero kicker="EXPLORE" title={lang==='ar'?'وجهات نختارها معك.':'Destinations, chosen with you.'} text={lang==='ar'?'استلهم من الوجهات ثم دعنا نبني النسخة التي تناسبك.':'Get inspired, then let us tailor the version that fits you.'}/><section className="section"><div className="container dest-grid big">{destinations.map(d=><Link to={d.slug==='umrah'?'/omra':'/destinations/'+d.slug} className="dest-card" key={d.slug}><img src={d.image} alt={d.title}/><div><small>{d.count}</small><h3>{lang==='ar'?d.title:d.fr}</h3><span>{lang==='ar'?'استكشف الوجهة':'Explore destination'} <ArrowLeft size={15}/></span></div></Link>)}</div></section></> }
function DestinationDetail({lang}:{lang:Lang}) { const {slug}=useParams(); const d=destinations.find(x=>x.slug===slug)||destinations[0]; return <><PageHero kicker="DESTINATION" title={lang==='ar'?d.title:d.fr} text={d.count} image={d.image}/><section className="section"><div className="container detail-copy"><div className="eyebrow">DISCOVER</div><h2>{lang==='ar'?'نصنع لك برنامجًا، لا مجرد قائمة أماكن.':'We build an itinerary, not just a list of places.'}</h2><p>{lang==='ar'?'أخبرنا عن المدة، نوع الفندق، الأنشطة التي تحبها وعدد المسافرين. سنستخدم هذه المعلومات لبناء تصور أوضح للرحلة.':'Tell us your dates, hotel style, favourite activities and number of travellers. We use that to shape a clearer trip concept.'}</p><Link className="btn btn-primary" to="/contact">{lang==='ar'?'خطط لهذه الوجهة':'Plan this destination'} <ArrowLeft size={18}/></Link></div></section></> }

function Umrah({lang}:{lang:Lang}) { return <><PageHero kicker="SPIRITUAL JOURNEY" title={lang==='ar'?'العمرة، بتنظيم يترك لك مساحة للعبادة.':'Omra, organized around what matters.'} text={lang==='ar'?'معلومات واضحة ومرافقة عملية من التخطيط إلى السفر.':'Clear information and practical support from planning to departure.'} image={images.umrah}/><section className="section"><div className="container umrah-grid"><div><div className="eyebrow">OMRA EXPERIENCE</div><h2>{lang==='ar'?'كل التفاصيل المهمة في مكان واحد.':'The important details, in one place.'}</h2><p>{lang==='ar'?'نساعدك في فهم البرنامج والخدمات المطلوبة، ثم نؤكد كل التفاصيل والأسعار قبل أي حجز.':'We help you understand the program and services, then confirm every detail and price before booking.'}</p><div className="feature-list"><span><Check/> {lang==='ar'?'برامج قابلة للتخصيص':'Flexible programs'}</span><span><Check/> {lang==='ar'?'خيارات إقامة وتنقل':'Stay & transfer options'}</span><span><Check/> {lang==='ar'?'مرافقة واضحة':'Clear assistance'}</span><span><Check/> {lang==='ar'?'تأكيد قبل الدفع':'Confirmation before payment'}</span></div><Link className="btn btn-primary" to="/contact">{lang==='ar'?'استفسر عن العمرة':'Ask about Omra'} <ArrowLeft size={18}/></Link></div><div className="umrah-visual"><img src={images.umrah} alt=""/><div className="floating-card"><HeartHandshake/><b>{lang==='ar'?'رحلة بروح مطمئنة':'A calmer journey'}</b><small>{lang==='ar'?'نرتب التفاصيل معك':'We arrange the details with you'}</small></div></div></div></section></> }

function Services({lang}:{lang:Lang}) { return <><PageHero kicker="OUR SERVICES" title={lang==='ar'?'كل ما تحتاجه للسفر، في مكان واحد.':'Everything you need to travel, in one place.'} text={lang==='ar'?'خدمات مترابطة تجعل التخطيط أقل تعقيدًا.':'Connected services that make planning simpler.'}/><section className="section"><div className="container service-grid">{services.map(([title,text,Icon])=>{const I=Icon as typeof Sparkles;return <div className="service-card" key={title as string}><span className="iconbox"><I size={22}/></span><h3>{title as string}</h3><p>{text as string}</p><ArrowRight size={18}/></div>})}</div></section><FinalCTA lang={lang}/></> }
function About({lang}:{lang:Lang}) { return <><PageHero kicker="ABOUT MAAROUF TOUR" title={lang==='ar'?'السفر الجيد يبدأ بالاستماع.':'Good travel starts with listening.'} text={lang==='ar'?'علامة سفر تضع الوضوح والمرونة والاهتمام بالتفاصيل في المقدمة.':'A travel brand built around clarity, flexibility and attention to detail.'}/><section className="section"><div className="container about-grid"><div><div className="eyebrow">OUR PROMISE</div><h2>{lang==='ar'?'نريد أن تشعر أن هناك شخصًا يهتم فعلًا برحلتك.':'We want you to feel that someone genuinely cares about your journey.'}</h2></div><div><p>{lang==='ar'?'نعمل على تبسيط قرارات السفر: نفهم طلبك، نقترح الخيارات، ننسق التفاصيل ونبقى قريبين عندما تحتاجنا. الموقع نفسه صُمم ليكون نقطة بداية سريعة وواضحة، وليس بديلًا عن الاستشارة البشرية.':'We simplify travel decisions: understand your request, suggest options, coordinate details and stay close when you need us. This website is a clear starting point, not a replacement for human advice.'}</p><div className="values"><span><ShieldCheck/> <b>Clarity</b></span><span><HeartHandshake/> <b>Care</b></span><span><Sparkles/> <b>Flexibility</b></span></div></div></div></section></> }
function FAQ({lang}:{lang:Lang}) { const [open,setOpen]=useState(0); return <><PageHero kicker="FAQ" title={lang==='ar'?'أسئلة قبل أن تبدأ.':'Questions before you start.'} text={lang==='ar'?'إجابات مختصرة على أكثر الأسئلة شيوعًا.':'Short answers to common questions.'}/><section className="section"><div className="container faq">{faqs.map(([q,a],i)=><button className={open===i?'faq-item active':'faq-item'} key={q} onClick={()=>setOpen(open===i?-1:i)}><div><span>0{i+1}</span><b>{lang==='ar'?q:['Can I request a fully tailored trip?','Are displayed prices final?','Can I contact you on WhatsApp?','Do you offer Omra programs?'][i]}</b></div><ChevronDown/></button>)}</div></section></> }
function Contact({lang}:{lang:Lang}) { const [sent,setSent]=useState(false); const submit=(e:FormEvent)=>{e.preventDefault();setSent(true)}; return <><PageHero kicker="LET’S TALK" title={lang==='ar'?'أخبرنا بما تفكر فيه.':'Tell us what you have in mind.'} text={lang==='ar'?'أرسل طلبك وسنعود إليك بتفاصيل أوضح.':'Send your request and we’ll come back with clearer options.'}/><section className="section"><div className="container contact-grid"><form className="contact-form" onSubmit={submit}>{sent?<div className="success"><Check/><h3>{lang==='ar'?'وصل طلبك بنجاح.':'Request received.'}</h3><p>{lang==='ar'?'هذه نسخة تجريبية؛ في الإنتاج يمكن ربط النموذج مباشرة بـCRM أو واتساب.':'Demo flow; in production this can connect directly to CRM or WhatsApp.'}</p><button type="button" className="btn btn-dark" onClick={()=>setSent(false)}>{lang==='ar'?'إرسال طلب آخر':'Send another request'}</button></div>:<><div className="form-row"><label>{lang==='ar'?'الاسم':'Name'}<input required placeholder={lang==='ar'?'اسمك الكامل':'Your name'}/></label><label>{lang==='ar'?'الهاتف':'Phone'}<input required type="tel" placeholder="05 xx xx xx xx"/></label></div><div className="form-row"><label>{lang==='ar'?'الوجهة':'Destination'}<input required placeholder={lang==='ar'?'أين تريد الذهاب؟':'Where do you want to go?'}/></label><label>{lang==='ar'?'عدد المسافرين':'Travellers'}<select><option>1</option><option>2</option><option>3</option><option>4+</option></select></label></div><label>{lang==='ar'?'تفاصيل إضافية':'Details'}<textarea rows={5} placeholder={lang==='ar'?'التاريخ، نوع الفندق، الميزانية التقريبية...':'Dates, hotel style, approximate budget...'}/></label><button className="btn btn-primary" type="submit">{lang==='ar'?'أرسل طلبي':'Send request'} <ArrowLeft size={18}/></button></>}</form><aside className="contact-aside"><div className="eyebrow">CONTACT</div><h2>{lang==='ar'?'أسرع طريق إلى رحلة أوضح.':'The fastest route to a clearer trip.'}</h2><a href={WHATSAPP} target="_blank" rel="noreferrer"><MessageCircle/> <span><b>WhatsApp</b><small>{lang==='ar'?'محادثة سريعة':'Quick conversation'}</small></span><ArrowLeft/></a><a href={'tel:'+PHONE.replaceAll(' ','')}><Phone/> <span><b>{PHONE}</b><small>{lang==='ar'?'اتصال مباشر':'Direct call'}</small></span><ArrowLeft/></a><a href={'mailto:'+EMAIL}><Mail/> <span><b>{EMAIL}</b><small>Email</small></span><ArrowLeft/></a><div className="address"><MapPin/><span>{lang==='ar'?'الجزائر — معلومات الفرع تُثبت قبل الإطلاق النهائي.':'Algeria — branch details to be confirmed before final launch.'}</span></div></aside></div></section></> }
function NotFound({lang}:{lang:Lang}) { return <section className="notfound"><div className="container"><div className="eyebrow">404</div><h1>{lang==='ar'?'هذه الصفحة سافرت بعيدًا.':'This page travelled away.'}</h1><Link className="btn btn-primary" to="/">{lang==='ar'?'العودة للرئيسية':'Back home'} <ArrowLeft/></Link></div></section> }

function Footer({lang}:{lang:Lang}) { return <footer><div className="container footer-grid"><div><Link className="brand footer-brand" to="/"><span className="brand-mark"><Plane size={19}/></span><span><b>Maarouf</b><small>TOUR & TRAVEL</small></span></Link><p>{lang==='ar'?'تجارب سفر أوضح، مصممة حولك.':'Clearer travel experiences, designed around you.'}</p><div className="social"><a href={WHATSAPP}><MessageCircle/></a><a href="https://instagram.com" target="_blank" rel="noreferrer"><Instagram/></a></div></div><div><b>{lang==='ar'?'استكشف':'Explore'}</b><Link to="/offres">{lang==='ar'?'العروض':'Offers'}</Link><Link to="/destinations">{lang==='ar'?'الوجهات':'Destinations'}</Link><Link to="/omra">{lang==='ar'?'العمرة':'Omra'}</Link></div><div><b>{lang==='ar'?'الشركة':'Company'}</b><Link to="/services">{lang==='ar'?'خدماتنا':'Services'}</Link><Link to="/a-propos">{lang==='ar'?'عن الشركة':'About'}</Link><Link to="/faq">FAQ</Link></div><div><b>{lang==='ar'?'تواصل':'Contact'}</b><a href={'tel:'+PHONE.replaceAll(' ','')}>{PHONE}</a><a href={'mailto:'+EMAIL}>{EMAIL}</a><a href={WHATSAPP}>WhatsApp</a></div></div><div className="container footer-bottom"><span>© 2026 Maarouf Tour. {lang==='ar'?'جميع الحقوق محفوظة.':'All rights reserved.'}</span><span>{lang==='ar'?'موقع تجريبي — المحتوى والأسعار تحتاج تأكيدًا قبل الإطلاق.':'Demo website — content and pricing require confirmation before launch.'}</span></div></footer> }
function MobileNav({lang}:{lang:Lang}) { const loc=useLocation(); const items=[['/','الرئيسية',Navigation],['/offres','العروض',Sparkles],['/omra','العمرة',HeartHandshake],['/contact','تواصل',MessageCircle]]; return <nav className="mobile-nav">{items.map(([href,label,Icon])=>{const I=Icon as typeof Navigation;return <Link className={loc.pathname===href?'active':''} to={href as string} key={href as string}><I size={19}/><span>{lang==='ar'?label:['Home','Offers','Omra','Contact'][items.findIndex(x=>x[0]===href)]}</span></Link>})}</nav> }

export default function Root(){return <BrowserRouter><App/></BrowserRouter>}
